Update to 1.18
Blobanium/Loading-Timer pull request #33
Opened 2021-12-18 12:19 UTC by xanthian

Added en_gb language
updated fabric.mod.json to match 1.18 requirements and updated loader version to cover log4j exploit.
added a new icon
removed vanguard dep as its dead

2021-12-18 19:52 UTC, Blobanium requested changes
It looks like the build failed (as it seems to run into a bad gateway error emanating from the Ladysnake lib(A.K.A. Vanguard's Library)). Consider removing the maven repo located [here](https://github.com/xanthian/Loading-Timer/blob/23ac92feba193f64fca5b2885c520b5d34ffd54e/build.gradle#L16). 

Also if you want, id recommend changing up build.gradle and gradle.properties a little bit to make sure compilation doesn't fail and Minecraft will start up correctly.

2021-12-22 23:47 UTC, Lord-Memester commented
Eagerly awaiting the day this update comes to be :D

(Also, vanguard caused problems for me a while ago--on the user end, anyway. Perhaps look into a different auto-update library?)

2021-12-22 23:54 UTC, Blobanium commented
> Eagerly awaiting the day this update comes to be :D
> 
> (Also, vanguard caused problems for me a while ago--on the user end, anyway. Perhaps look into a different auto-update library?)

Nah, Auto-update for mods is kind of a horrible idea for modpacks anyway.

2021-12-23 09:55 UTC, xanthian commented
Sadly my pr was the extent of my knowledge.
I don't know about updating gradle so unfortunately please decline this pr and someone else will have to take over

2021-12-30 00:18 UTC, Blobanium commented
Don't mind the compiler failure, it failed because the java compiler is outdated. I can update this myself. But if you want to do it yourself, you can change [this](https://github.com/Blobanium/Loading-Timer/blob/8cd52628c45486a76c47a3cca0da32c52bd9abc3/.github/workflows/build.yml#L15)
To 17. However I still need to check if there isn't any other compilation issues that are present (hopefully there isn't any). I'll get back to you if theirs anything else that needs to he changed.

2021-12-30 02:23 UTC, Blobanium approved these changes
Looking good! Do you need to add in anything else before this PR gets merged?

2021-12-30 22:30 UTC, Blobanium commented
alrighty, the compiler is compiling it properly and this PR ready to merge! Ready when you are.

2021-12-30 23:04 UTC, xanthian commented
good to go!

2021-12-31 02:29 UTC, merged